### PR TITLE
Compatibility with Redmine 3.1.0

### PR DESCRIPTION
**Pull request by phoebusnetto**

### CODE REVIEW

**Comment by phoebusnetto** [comment]
I couldn't see why CI brokes.

The page shows "There was an error while loading data, please try again."

**Comment by bluenevus** [comment]
phoebusnetto.  I'm trying to use your 3.1 compatibility branch but it doesn't work.  It work when I first installed then created a test report.  after that 1 test report, it errors out.  I didn't do anything...just tried to make a 2nd one.  I could really use some help.  You have no way to log issues on your fork so this is the best I can do to ask.  here is the error log

Started POST "/projects/xxxxx/custom_reports" for xxxxxxxxxx at 2016-04-27 01:09:30 +0000
Processing by CustomReportsController#create as HTML
  Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"xxxxxxxxxx", "custom_report"=>{"name"=>"Issues by ", "description"=>"", "chart_type"=>"pie", "is_public"=>"0", "group_by"=>"", "null_text"=>"Null", "series_attributes"=>{"0"=>{"name"=>"", "flt"=>{"f"=>["status_id", ""], "op"=>{"status_id"=>"o", "project_id"=>"=", "tracker_id"=>"=", "priority_id"=>"=", "author_id"=>"=", "assigned_to_id"=>"=", "member_of_group"=>"=", "assigned_to_role"=>"=", "fixed_version_id"=>"=", "category_id"=>"=", "subject"=>"~", "description"=>"~", "created_on"=>"=", "updated_on"=>"=", "closed_on"=>"=", "start_date"=>"=", "due_date"=>"=", "done_ratio"=>"=", "is_private"=>"=", "watcher_id"=>"=", "relates"=>"=", "duplicates"=>"=", "duplicated"=>"=", "blocks"=>"=", "blocked"=>"=", "precedes"=>"=", "follows"=>"=", "copied_to"=>"=", "copied_from"=>"=", "parent_id"=>"=", "child_id"=>"=", "contacts"=>"=", "companies"=>"=", "deal"=>"=", "customer"=>"=", "ticket_source"=>"=", "customer_company"=>"=", "ticket_reaction_time"=>"=", "ticket_first_response_time"=>"=", "ticket_resolve_time"=>"=", "vote"=>"="}, "v"=>{"project_id"=>["mine"], "tracker_id"=>["14"], "priority_id"=>["1"], "author_id"=>["me"], "assigned_to_id"=>["me"], "member_of_group"=>["24"], "assigned_to_role"=>["3"], "subject"=>[""], "description"=>[""], "created_on"=>[""], "updated_on"=>[""], "closed_on"=>[""], "start_date"=>[""], "due_date"=>[""], "done_ratio"=>[""], "is_private"=>["1"], "watcher_id"=>["me"], "contacts"=>["30"], "deal"=>[""], "customer"=>["30"], "ticket_source"=>["0"], "customer_company"=>[""], "ticket_reaction_time"=>[""], "ticket_first_response_time"=>[""], "ticket_resolve_time"=>[""], "vote"=>["2"]}}, "_destroy"=>"false"}}}, "commit"=>"Create", "project_id"=>"xxxxx"}
  Current user: xxxxxx (id=x)
Completed 500 Internal Server Error in 10ms (ActiveRecord: 3.5ms)

ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by phoebusnetto** [comment]
@bluenevus, hi!

Could you post the error on **production.log** file?
I remember a problem about the permissions, but can't tell if is the same you got.

**Comment by bluenevus** [comment]
Started POST "/projects/xxxxx/custom_reports" for xxxxxxxxxx at 2016-04-27 01:09:30 +0000
Processing by CustomReportsController#create as HTML
Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"xxxxxxxxxx", "custom_report"=>{"name"=>"Issues by ", "description"=>"", "chart_type"=>"pie", "is_public"=>"0", "group_by"=>"", "null_text"=>"Null", "series_attributes"=>{"0"=>{"name"=>"", "flt"=>{"f"=>["status_id", ""], "op"=>{"status_id"=>"o", "project_id"=>"=", "tracker_id"=>"=", "priority_id"=>"=", "author_id"=>"=", "assigned_to_id"=>"=", "member_of_group"=>"=", "assigned_to_role"=>"=", "fixed_version_id"=>"=", "category_id"=>"=", "subject"=>"~", "description"=>"~", "created_on"=>"=", "updated_on"=>"=", "closed_on"=>"=", "start_date"=>"=", "due_date"=>"=", "done_ratio"=>"=", "is_private"=>"=", "watcher_id"=>"=", "relates"=>"=", "duplicates"=>"=", "duplicated"=>"=", "blocks"=>"=", "blocked"=>"=", "precedes"=>"=", "follows"=>"=", "copied_to"=>"=", "copied_from"=>"=", "parent_id"=>"=", "child_id"=>"=", "contacts"=>"=", "companies"=>"=", "deal"=>"=", "customer"=>"=", "ticket_source"=>"=", "customer_company"=>"=", "ticket_reaction_time"=>"=", "ticket_first_response_time"=>"=", "ticket_resolve_time"=>"=", "vote"=>"="}, "v"=>{"project_id"=>["mine"], "tracker_id"=>["14"], "priority_id"=>["1"], "author_id"=>["me"], "assigned_to_id"=>["me"], "member_of_group"=>["24"], "assigned_to_role"=>["3"], "subject"=>[""], "description"=>[""], "created_on"=>[""], "updated_on"=>[""], "closed_on"=>[""], "start_date"=>[""], "due_date"=>[""], "done_ratio"=>[""], "is_private"=>["1"], "watcher_id"=>["me"], "contacts"=>["30"], "deal"=>[""], "customer"=>["30"], "ticket_source"=>["0"], "customer_company"=>[""], "ticket_reaction_time"=>[""], "ticket_first_response_time"=>[""], "ticket_resolve_time"=>[""], "vote"=>["2"]}}, "_destroy"=>"false"}}}, "commit"=>"Create", "project_id"=>"xxxxx"}
Current user: xxxxxx (id=x)
Completed 500 Internal Server Error in 10ms (ActiveRecord: 3.5ms)
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

This is what happens every time I run it.

--
Vr Frank

**Comment by bluenevus** [comment]
specifically, this issue 
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by nodecarter** [comment]
Hi @phoebusnetto! Thanks for PR. I have fixed plugin for redmine 3.x compatibility.
@bluenevus try the latest version of plugin from master branch.
I will close this issue.

**Comment by phoebusnetto** [comment]
Hi @nodecarter!

Awesome! I'll try the master branch!

Thank you a lot!

**Pull request closed without merging**
